name: Release Java Files as ZIP

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'    # Trigger on version tags like v1.0, v2.1.3 etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare java files
        run: |
          mkdir java-extracted
          cp -r java/* java-extracted/

      - name: Create ZIP archive
        run: |
          zip -r Good-Creations-Resource-Pack-Java.zip java-extracted

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: Good-Creations-Resource-Pack-Java.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
